#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

set -euxo pipefail

VERSION="$1"
BOOTDIR=/boot

command -v update-mkosi-debinit >/dev/null 2>&1 || exit 0

# passing the kernel version is required
if [ -z "${VERSION}" ]; then
    echo >&2 "W: mkosi-debinit: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
    exit 2
fi

# exit if custom kernel does not need an initramfs
[ "${INITRD:-}" = 'No' ] && exit 0

# absolute file name of kernel image may be passed as a second argument;
# create the initrd in the same directory
if [ -n "${2:-}" ]; then
	BOOTDIR=$(dirname "$2")
fi

# avoid running multiple times
if [ -n "${DEB_MAINT_PARAMS:-}" ]; then
    eval set -- "$DEB_MAINT_PARAMS"
    if [ -z "$1" ] || [ "$1" != "configure" ]; then
            exit 0
    fi
fi

# we're good - create initramfs
echo "mkosi-debinit: Generating $BOOTDIR/initrd.img-$VERSION"
update-mkosi-debinit "$BOOTDIR"/initrd.img-"$VERSION" "$VERSION" >&2
