#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

set -euxo pipefail

VERSION="$1"
BOOTDIR=/boot

# passing the kernel version is required
[ -z "${VERSION}" ] && exit 0

# absolute file name of kernel image may be passed as a second argument;
# remove the initrd from the same directory
if [ -n "${2:-}" ]; then
	BOOTDIR=$(dirname "$2")
fi

# avoid running multiple times
if [ -n "${DEB_MAINT_PARAMS:-}" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "remove" ]; then
		exit 0
	fi
fi


# delete initramfs
rm -f "$BOOTDIR/initrd.img-${VERSION}"
