---
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Deploy Repo
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  deploy:
    if: github.repository == 'seb-schulz/mkosi-debinit'
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Repository checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Build repository
        run: |
          export GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)"
          mkdir -p "$GNUPGHOME" && chmod 0700 $GNUPGHOME
          echo "${{ secrets.SIGNKEY }}" | gpg --import

          ./scripts/build-repo.sh
          find $GNUPGHOME -type f -exec shred {} \;
          rm -fr $GNUPGHOME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload repository
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: repo/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5
