---
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Deploy Repo
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  deploy:
    if: github.repository == 'seb-schulz/mkosi-debinit'
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Repository checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build repository
        run: |
          export GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)"
          mkdir -p "$GNUPGHOME" && chmod 0700 $GNUPGHOME
          echo "${{ secrets.SIGNKEY }}" | gpg --import

          ./scripts/build-repo.sh
          find $GNUPGHOME -type f -exec shred {} \;
          rm -fr $GNUPGHOME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload repository
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: repo/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
