---
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Deploy Repo
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  deploy:
    if: github.repository == 'seb-schulz/mkosi-debinit'
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
      - name: Build repository
        run: ./scripts/build-repo.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload repository
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
