---
# SPDX-License-Identifier: LGPL-2.1-or-later

name: Release
on:
  push:
    branches:
      - main
    paths:
      - "debian/changelog"
jobs:
  check:
    if: github.repository == 'seb-schulz/mkosi-debinit'
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      eligable: ${{ steps.eligability.outputs.eligable || false }}
    steps:
      - name: Repository checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Check eligability
        id: eligability
        run: |
          command -v dpkg-parsechangelog >/dev/null 2>&1 || exit 1
          [[ $(dpkg-parsechangelog -SDistribution) = 'UNRELEASED' ]] || echo "eligable=true" >> "$GITHUB_OUTPUT"
  build-and-release:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs: check
    if: needs.check.outputs.eligable == 'true'
    steps:
      - name: Repository checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Build packages
        run: make build
        env:
          WITH_PODMAN: 1
      - name: Build packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y pandoc
          ./scripts/do-release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
